from typing import Protocol
from backend.app.orchestrator.schemas import RouteDecision
from backend.app.voice.schemas import CapabilityResult

class VoiceCapabilityBackend(Protocol):
    def execute(self,decision:RouteDecision)->CapabilityResult:...
    def prepare_write(self,tool_name:str,arguments:dict)->CapabilityResult:...
    def confirm_write(self,tool_name:str,arguments:dict,confirmation_token:str)->CapabilityResult:...
